
// Objective-C API for talking to the following Go packages
//
//	bore-demo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bore_FRAMEWORK_H__
#define __Bore_FRAMEWORK_H__

#include "Boredemo.objc.h"
#include "Universe.objc.h"

#endif
